### ISSUE TITLE
--url not taken into account

### ISSUE THREAD

**Issue by baphony** [finos/SymphonyElectron#1537]
**Describe the bug**

The `--url=https://local-dev.symphony.com:9090/` is not taken into account:

If I revert this commit:
df14fa19 SDA-3901 (Add new implementation for welcome screen) (#1519)
It works as expected.

window.location.href gives:
'file:///C:/Users/.../SymphonyElectron/lib/src/renderer/react-window.html?componentName=welcome&locale=fr-FR&title=Bienvenue'
It should be  'https://local-dev.symphony.com:9090/' instead.

**To Reproduce**

```
SymphonyElectron> npm run dev -- --url=https://local-dev.symphony.com:9090/
```

That's the exact command I am using on Windows 10 in Powershell:
```
SymphonyElectron> npm run dev --- --url=https://local-dev.symphony.com:9090/ --c9pipe=testpipe
```

**Expected behavior**

It should display the login page of pod target by the --url parameter (either local, st3...).

window.location.href => 'https://local-dev.symphony.com:9090/'

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App Version
POD: local-dev.symphony.com
SBE: 2.0.1 (0)
SDA: 20.0.0 (0)
SFE: 0

**Comment by sbenmoussati** [comment]
Reverted the commit. Thank you!
